ROBOT_FRAME: "base_link"
GOAL_FRAME_ID: "map"

MAX_VELOCITY: 0.2
MIN_VELOCITY: 0.0
MAX_YAWRATE: 0.4
MAX_ACCELERATION: 1.0


PREDICT_TIME: 4.0
DT : 0.1
OBS_RANGE: 1.2
VELOCITY_SAMPLES: 4
YAWRATE_SAMPLES: 16
OBS_TH: 0.005

MAX_DECELERATION: 1.0
MAX_D_YAWRATE: 2.0

OBSTACLE_COST_GAIN: 1.0
DIST_COST_GAIN: 0.70
DIRECTION_COST_GAIN: 0.20

GOAL_THRESHOLD: 0.5
ANGLE_THRESHLD: 0.05

#14,9 /1.0,-6.5
X_1: 4.0
Y_1: -1.0
YAW_1: -1.0

